/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_window_admin (void);
GtkWidget* create_menu_window_admin (void);
GtkWidget* create_traitment_window_admin (void);
GtkWidget* create_affiche_window_admin (void);
GtkWidget* create_exist_window_admin (void);
GtkWidget* create_not_exist_window_admin (void);
GtkWidget* create_panne_window_admin (void);
GtkWidget* create_panne_recherche_window_admin (void);
GtkWidget* create_window1_admin (void);
