/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_window_admin (void)
{
  GtkWidget *ajout_window_admin;
  GtkWidget *fixed1;
  GtkWidget *entry_nom_admin;
  GtkWidget *entry_id_admin;
  GtkWidget *entry_id_ancient_admin;
  GtkWidget *etudiant_radio;
  GSList *etudiant_radio_group = NULL;
  GtkWidget *foyer_radio;
  GtkWidget *restau_radio;
  GtkWidget *nutr_radio;
  GtkWidget *tech_radio;
  GtkWidget *admin_radio;
  GtkWidget *id;
  GtkWidget *role;
  GtkWidget *id_ancient;
  GtkWidget *ajout;
  GtkWidget *nom;
  GtkWidget *modifie_button_admin;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label17;
  GtkWidget *ajout_button_admin;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *return_ajout_button_admin;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;

  ajout_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_window_admin), _("ajout_window"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_window_admin), fixed1);

  entry_nom_admin = gtk_entry_new ();
  gtk_widget_show (entry_nom_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom_admin, 136, 104);
  gtk_widget_set_size_request (entry_nom_admin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_admin), 8226);

  entry_id_admin = gtk_entry_new ();
  gtk_widget_show (entry_id_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_admin, 136, 160);
  gtk_widget_set_size_request (entry_id_admin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_admin), 8226);

  entry_id_ancient_admin = gtk_entry_new ();
  gtk_widget_show (entry_id_ancient_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_ancient_admin, 16, 336);
  gtk_widget_set_size_request (entry_id_ancient_admin, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_ancient_admin), 8226);

  etudiant_radio = gtk_radio_button_new_with_mnemonic (NULL, _("etudiant"));
  gtk_widget_show (etudiant_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), etudiant_radio, 288, 216);
  gtk_widget_set_size_request (etudiant_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (etudiant_radio), etudiant_radio_group);
  etudiant_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (etudiant_radio));

  foyer_radio = gtk_radio_button_new_with_mnemonic (NULL, _("agent foyer"));
  gtk_widget_show (foyer_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), foyer_radio, 128, 256);
  gtk_widget_set_size_request (foyer_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (foyer_radio), etudiant_radio_group);
  etudiant_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (foyer_radio));

  restau_radio = gtk_radio_button_new_with_mnemonic (NULL, _("agent restaurant"));
  gtk_widget_show (restau_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), restau_radio, 280, 256);
  gtk_widget_set_size_request (restau_radio, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (restau_radio), etudiant_radio_group);
  etudiant_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (restau_radio));

  nutr_radio = gtk_radio_button_new_with_mnemonic (NULL, _("nutritian"));
  gtk_widget_show (nutr_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), nutr_radio, 288, 296);
  gtk_widget_set_size_request (nutr_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (nutr_radio), etudiant_radio_group);
  etudiant_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (nutr_radio));

  tech_radio = gtk_radio_button_new_with_mnemonic (NULL, _("technician"));
  gtk_widget_show (tech_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), tech_radio, 136, 296);
  gtk_widget_set_size_request (tech_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (tech_radio), etudiant_radio_group);
  etudiant_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (tech_radio));

  admin_radio = gtk_radio_button_new_with_mnemonic (NULL, _("admin"));
  gtk_widget_show (admin_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), admin_radio, 136, 216);
  gtk_widget_set_size_request (admin_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (admin_radio), etudiant_radio_group);
  etudiant_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (admin_radio));

  id = gtk_label_new (_("id"));
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed1), id, 48, 168);
  gtk_widget_set_size_request (id, 41, 17);

  role = gtk_label_new (_("role"));
  gtk_widget_show (role);
  gtk_fixed_put (GTK_FIXED (fixed1), role, 48, 224);
  gtk_widget_set_size_request (role, 48, 16);

  id_ancient = gtk_label_new (_("id_ancient"));
  gtk_widget_show (id_ancient);
  gtk_fixed_put (GTK_FIXED (fixed1), id_ancient, 16, 312);
  gtk_widget_set_size_request (id_ancient, 72, 17);

  ajout = gtk_label_new (_("Ajout"));
  gtk_widget_show (ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout, 104, 32);
  gtk_widget_set_size_request (ajout, 216, 40);
  gtk_label_set_width_chars (GTK_LABEL (ajout), 5);

  nom = gtk_label_new (_("nom"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 48, 104);
  gtk_widget_set_size_request (nom, 48, 24);

  modifie_button_admin = gtk_button_new ();
  gtk_widget_show (modifie_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), modifie_button_admin, 8, 376);
  gtk_widget_set_size_request (modifie_button_admin, 104, 37);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (modifie_button_admin), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("modifie"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  ajout_button_admin = gtk_button_new ();
  gtk_widget_show (ajout_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_button_admin, 176, 360);
  gtk_widget_set_size_request (ajout_button_admin, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajout_button_admin), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("ajout"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  return_ajout_button_admin = gtk_button_new ();
  gtk_widget_show (return_ajout_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), return_ajout_button_admin, 344, 400);
  gtk_widget_set_size_request (return_ajout_button_admin, 82, 24);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (return_ajout_button_admin), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) etudiant_radio, "toggled",
                    G_CALLBACK (on_etudiant_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) foyer_radio, "toggled",
                    G_CALLBACK (on_foyer_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) restau_radio, "toggled",
                    G_CALLBACK (on_restau_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) nutr_radio, "toggled",
                    G_CALLBACK (on_nutr_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) tech_radio, "toggled",
                    G_CALLBACK (on_tech_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) admin_radio, "toggled",
                    G_CALLBACK (on_admin_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) modifie_button_admin, "clicked",
                    G_CALLBACK (on_modifie_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_button_admin, "clicked",
                    G_CALLBACK (on_ajout_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) return_ajout_button_admin, "clicked",
                    G_CALLBACK (on_return_ajout_button_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_window_admin, ajout_window_admin, "ajout_window_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, entry_nom_admin, "entry_nom_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, entry_id_admin, "entry_id_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, entry_id_ancient_admin, "entry_id_ancient_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, etudiant_radio, "etudiant_radio");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, foyer_radio, "foyer_radio");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, restau_radio, "restau_radio");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, nutr_radio, "nutr_radio");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, tech_radio, "tech_radio");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, admin_radio, "admin_radio");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, id, "id");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, role, "role");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, id_ancient, "id_ancient");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, nom, "nom");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, modifie_button_admin, "modifie_button_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, image11, "image11");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, ajout_button_admin, "ajout_button_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, return_ajout_button_admin, "return_ajout_button_admin");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajout_window_admin, label7, "label7");

  return ajout_window_admin;
}

GtkWidget*
create_menu_window_admin (void)
{
  GtkWidget *menu_window_admin;
  GtkWidget *fixed2;
  GtkWidget *menu_title;
  GtkWidget *menu_modifie_button_admin;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label19;
  GtkWidget *menu_supprime_button_admin;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label20;
  GtkWidget *menu_panne_button_admin;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label24;
  GtkWidget *menu_ajout_button_admin;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label18;
  GtkWidget *menu_recherche_button_admin;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label21;
  GtkWidget *menu_affiche_button_admin;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label22;

  menu_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu_window_admin), _("menu_window"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (menu_window_admin), fixed2);

  menu_title = gtk_text_view_new ();
  gtk_widget_show (menu_title);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_title, 176, 32);
  gtk_widget_set_size_request (menu_title, 96, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (menu_title)), _("menu admin"), -1);

  menu_modifie_button_admin = gtk_button_new ();
  gtk_widget_show (menu_modifie_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_modifie_button_admin, 224, 72);
  gtk_widget_set_size_request (menu_modifie_button_admin, 176, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (menu_modifie_button_admin), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("fen\303\250tre modification"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox13), label19, FALSE, FALSE, 0);

  menu_supprime_button_admin = gtk_button_new ();
  gtk_widget_show (menu_supprime_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_supprime_button_admin, 224, 136);
  gtk_widget_set_size_request (menu_supprime_button_admin, 178, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (menu_supprime_button_admin), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("fen\303\250tre de supprission"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox14), label20, FALSE, FALSE, 0);

  menu_panne_button_admin = gtk_button_new ();
  gtk_widget_show (menu_panne_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_panne_button_admin, 136, 248);
  gtk_widget_set_size_request (menu_panne_button_admin, 168, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (menu_panne_button_admin), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("\303\251tage en panne"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox18), label24, FALSE, FALSE, 0);

  menu_ajout_button_admin = gtk_button_new ();
  gtk_widget_show (menu_ajout_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_ajout_button_admin, 32, 72);
  gtk_widget_set_size_request (menu_ajout_button_admin, 168, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (menu_ajout_button_admin), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("fen\303\250tre d'ajout"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox12), label18, FALSE, FALSE, 0);

  menu_recherche_button_admin = gtk_button_new ();
  gtk_widget_show (menu_recherche_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_recherche_button_admin, 32, 136);
  gtk_widget_set_size_request (menu_recherche_button_admin, 176, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (menu_recherche_button_admin), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("fen\303\250tre de recherche"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox15), label21, FALSE, FALSE, 0);

  menu_affiche_button_admin = gtk_button_new ();
  gtk_widget_show (menu_affiche_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), menu_affiche_button_admin, 136, 200);
  gtk_widget_set_size_request (menu_affiche_button_admin, 168, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (menu_affiche_button_admin), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("fen\303\250tre d'affichage"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox16), label22, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) menu_modifie_button_admin, "clicked",
                    G_CALLBACK (on_menu_modifie_button_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) menu_supprime_button_admin, "clicked",
                    G_CALLBACK (on_menu_supprime_button_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) menu_panne_button_admin, "clicked",
                    G_CALLBACK (on_menu_panne_button_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) menu_ajout_button_admin, "clicked",
                    G_CALLBACK (on_menu_ajout_button_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) menu_recherche_button_admin, "clicked",
                    G_CALLBACK (on_menu_recherche_button_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) menu_affiche_button_admin, "clicked",
                    G_CALLBACK (on_menu_affiche_button_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu_window_admin, menu_window_admin, "menu_window_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_title, "menu_title");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_modifie_button_admin, "menu_modifie_button_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (menu_window_admin, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (menu_window_admin, image13, "image13");
  GLADE_HOOKUP_OBJECT (menu_window_admin, label19, "label19");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_supprime_button_admin, "menu_supprime_button_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (menu_window_admin, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (menu_window_admin, image14, "image14");
  GLADE_HOOKUP_OBJECT (menu_window_admin, label20, "label20");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_panne_button_admin, "menu_panne_button_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (menu_window_admin, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (menu_window_admin, image18, "image18");
  GLADE_HOOKUP_OBJECT (menu_window_admin, label24, "label24");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_ajout_button_admin, "menu_ajout_button_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (menu_window_admin, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (menu_window_admin, image12, "image12");
  GLADE_HOOKUP_OBJECT (menu_window_admin, label18, "label18");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_recherche_button_admin, "menu_recherche_button_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (menu_window_admin, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (menu_window_admin, image15, "image15");
  GLADE_HOOKUP_OBJECT (menu_window_admin, label21, "label21");
  GLADE_HOOKUP_OBJECT (menu_window_admin, menu_affiche_button_admin, "menu_affiche_button_admin");
  GLADE_HOOKUP_OBJECT (menu_window_admin, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (menu_window_admin, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (menu_window_admin, image16, "image16");
  GLADE_HOOKUP_OBJECT (menu_window_admin, label22, "label22");

  return menu_window_admin;
}

GtkWidget*
create_traitment_window_admin (void)
{
  GtkWidget *traitment_window_admin;
  GtkWidget *fixed3;
  GtkWidget *entry_id;
  GtkWidget *id;
  GtkWidget *supprime_button;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *recherche_button;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *return_traitment_button_admin;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label14;

  traitment_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (traitment_window_admin), _("traitment id"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (traitment_window_admin), fixed3);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_id, 104, 48);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  id = gtk_label_new (_("id"));
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed3), id, 16, 40);
  gtk_widget_set_size_request (id, 72, 40);

  supprime_button = gtk_button_new ();
  gtk_widget_show (supprime_button);
  gtk_fixed_put (GTK_FIXED (fixed3), supprime_button, 24, 120);
  gtk_widget_set_size_request (supprime_button, 120, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprime_button), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("supprime"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  recherche_button = gtk_button_new ();
  gtk_widget_show (recherche_button);
  gtk_fixed_put (GTK_FIXED (fixed3), recherche_button, 232, 120);
  gtk_widget_set_size_request (recherche_button, 112, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (recherche_button), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  return_traitment_button_admin = gtk_button_new ();
  gtk_widget_show (return_traitment_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed3), return_traitment_button_admin, 128, 192);
  gtk_widget_set_size_request (return_traitment_button_admin, 128, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (return_traitment_button_admin), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supprime_button, "clicked",
                    G_CALLBACK (on_supprime_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_button, "clicked",
                    G_CALLBACK (on_recherche_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) return_traitment_button_admin, "clicked",
                    G_CALLBACK (on_return_traitment_button_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (traitment_window_admin, traitment_window_admin, "traitment_window_admin");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, id, "id");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, supprime_button, "supprime_button");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, image5, "image5");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, label11, "label11");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, recherche_button, "recherche_button");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, image6, "image6");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, label12, "label12");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, return_traitment_button_admin, "return_traitment_button_admin");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, image8, "image8");
  GLADE_HOOKUP_OBJECT (traitment_window_admin, label14, "label14");

  return traitment_window_admin;
}

GtkWidget*
create_affiche_window_admin (void)
{
  GtkWidget *affiche_window_admin;
  GtkWidget *fixed4;
  GtkWidget *treeview;
  GtkWidget *refresh_button;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label15;
  GtkWidget *return_affiche_button_admin;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label16;

  affiche_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affiche_window_admin), _("affiche_window"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (affiche_window_admin), fixed4);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview, 8, 8);
  gtk_widget_set_size_request (treeview, 512, 216);

  refresh_button = gtk_button_new ();
  gtk_widget_show (refresh_button);
  gtk_fixed_put (GTK_FIXED (fixed4), refresh_button, 96, 256);
  gtk_widget_set_size_request (refresh_button, 96, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (refresh_button), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("refresh"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  return_affiche_button_admin = gtk_button_new ();
  gtk_widget_show (return_affiche_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed4), return_affiche_button_admin, 312, 264);
  gtk_widget_set_size_request (return_affiche_button_admin, 88, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (return_affiche_button_admin), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox10), label16, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) refresh_button, "clicked",
                    G_CALLBACK (on_refresh_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) return_affiche_button_admin, "clicked",
                    G_CALLBACK (on_return_affiche_button_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affiche_window_admin, affiche_window_admin, "affiche_window_admin");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, refresh_button, "refresh_button");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, image9, "image9");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, label15, "label15");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, return_affiche_button_admin, "return_affiche_button_admin");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, image10, "image10");
  GLADE_HOOKUP_OBJECT (affiche_window_admin, label16, "label16");

  return affiche_window_admin;
}

GtkWidget*
create_exist_window_admin (void)
{
  GtkWidget *exist_window_admin;
  GtkWidget *fixed5;
  GtkWidget *textview1;
  GtkWidget *treeviewexist;

  exist_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (exist_window_admin), _("exist_window"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (exist_window_admin), fixed5);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed5), textview1, 120, 16);
  gtk_widget_set_size_request (textview1, 144, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("utilisateur  existant"), -1);

  treeviewexist = gtk_tree_view_new ();
  gtk_widget_show (treeviewexist);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewexist, 48, 40);
  gtk_widget_set_size_request (treeviewexist, 312, 64);

  g_signal_connect ((gpointer) treeviewexist, "row_activated",
                    G_CALLBACK (on_treeviewexist_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (exist_window_admin, exist_window_admin, "exist_window_admin");
  GLADE_HOOKUP_OBJECT (exist_window_admin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (exist_window_admin, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (exist_window_admin, treeviewexist, "treeviewexist");

  return exist_window_admin;
}

GtkWidget*
create_not_exist_window_admin (void)
{
  GtkWidget *not_exist_window_admin;
  GtkWidget *fixed6;
  GtkWidget *textview2;

  not_exist_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (not_exist_window_admin), _("not_exist_window"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (not_exist_window_admin), fixed6);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_fixed_put (GTK_FIXED (fixed6), textview2, 96, 88);
  gtk_widget_set_size_request (textview2, 176, 80);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), _("utilisateur non exitstant"), -1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (not_exist_window_admin, not_exist_window_admin, "not_exist_window_admin");
  GLADE_HOOKUP_OBJECT (not_exist_window_admin, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (not_exist_window_admin, textview2, "textview2");

  return not_exist_window_admin;
}

GtkWidget*
create_panne_window_admin (void)
{
  GtkWidget *panne_window_admin;
  GtkWidget *fixed8;
  GtkWidget *treeviewpanneadmin;
  GtkWidget *return_panne_button_admin;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label28;
  GtkWidget *etage_panne_admin;

  panne_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (panne_window_admin), _("panne window"));
  gtk_window_set_default_size (GTK_WINDOW (panne_window_admin), 600, 400);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (panne_window_admin), fixed8);

  treeviewpanneadmin = gtk_tree_view_new ();
  gtk_widget_show (treeviewpanneadmin);
  gtk_fixed_put (GTK_FIXED (fixed8), treeviewpanneadmin, 128, 72);
  gtk_widget_set_size_request (treeviewpanneadmin, 0, 0);

  return_panne_button_admin = gtk_button_new ();
  gtk_widget_show (return_panne_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed8), return_panne_button_admin, 224, 312);
  gtk_widget_set_size_request (return_panne_button_admin, 96, 37);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (return_panne_button_admin), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox20), label28, FALSE, FALSE, 0);

  etage_panne_admin = gtk_label_new (_("etage en panne"));
  gtk_widget_show (etage_panne_admin);
  gtk_fixed_put (GTK_FIXED (fixed8), etage_panne_admin, 216, 40);
  gtk_widget_set_size_request (etage_panne_admin, 112, 16);

  g_signal_connect ((gpointer) treeviewpanneadmin, "row_activated",
                    G_CALLBACK (on_treeviewpanne_row_activated),
                    NULL);
  g_signal_connect ((gpointer) return_panne_button_admin, "clicked",
                    G_CALLBACK (on_return_panne_button_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (panne_window_admin, panne_window_admin, "panne_window_admin");
  GLADE_HOOKUP_OBJECT (panne_window_admin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (panne_window_admin, treeviewpanneadmin, "treeviewpanneadmin");
  GLADE_HOOKUP_OBJECT (panne_window_admin, return_panne_button_admin, "return_panne_button_admin");
  GLADE_HOOKUP_OBJECT (panne_window_admin, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (panne_window_admin, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (panne_window_admin, image20, "image20");
  GLADE_HOOKUP_OBJECT (panne_window_admin, label28, "label28");
  GLADE_HOOKUP_OBJECT (panne_window_admin, etage_panne_admin, "etage_panne_admin");

  return panne_window_admin;
}

GtkWidget*
create_panne_recherche_window_admin (void)
{
  GtkWidget *panne_recherche_window_admin;
  GtkWidget *fixed9;
  GtkObject *spinbutton_admin_adj;
  GtkWidget *spinbutton_admin;
  GtkWidget *panne_button_admin;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label27;
  GtkWidget *etage_admin;
  GtkWidget *jour_admin;
  GtkWidget *checkbutton_etage_admin;
  GtkWidget *checkbutton_jour_admin;
  GtkWidget *combobox_admin;

  panne_recherche_window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (panne_recherche_window_admin), _("recherche panne"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (panne_recherche_window_admin), fixed9);

  spinbutton_admin_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton_admin = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_admin_adj), 1, 0);
  gtk_widget_show (spinbutton_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton_admin, 128, 120);
  gtk_widget_set_size_request (spinbutton_admin, 60, 27);

  panne_button_admin = gtk_button_new ();
  gtk_widget_show (panne_button_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), panne_button_admin, 40, 184);
  gtk_widget_set_size_request (panne_button_admin, 184, 45);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (panne_button_admin), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("recherche le panne"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox19), label27, FALSE, FALSE, 0);

  etage_admin = gtk_label_new (_("etage"));
  gtk_widget_show (etage_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), etage_admin, 32, 48);
  gtk_widget_set_size_request (etage_admin, 64, 33);

  jour_admin = gtk_label_new (_("jour"));
  gtk_widget_show (jour_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), jour_admin, 40, 120);
  gtk_widget_set_size_request (jour_admin, 49, 17);

  checkbutton_etage_admin = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton_etage_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_etage_admin, 192, 48);
  gtk_widget_set_size_request (checkbutton_etage_admin, 118, 24);

  checkbutton_jour_admin = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton_jour_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_jour_admin, 192, 120);
  gtk_widget_set_size_request (checkbutton_jour_admin, 118, 24);

  combobox_admin = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_admin);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox_admin, 128, 48);
  gtk_widget_set_size_request (combobox_admin, 56, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_admin), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_admin), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_admin), _("3"));

  g_signal_connect ((gpointer) panne_button_admin, "clicked",
                    G_CALLBACK (on_panne_button_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_etage_admin, "toggled",
                    G_CALLBACK (on_checkbutton_etage_admin_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_jour_admin, "toggled",
                    G_CALLBACK (on_checkbutton_jour_admin_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (panne_recherche_window_admin, panne_recherche_window_admin, "panne_recherche_window_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, spinbutton_admin, "spinbutton_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, panne_button_admin, "panne_button_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, image19, "image19");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, label27, "label27");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, etage_admin, "etage_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, jour_admin, "jour_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, checkbutton_etage_admin, "checkbutton_etage_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, checkbutton_jour_admin, "checkbutton_jour_admin");
  GLADE_HOOKUP_OBJECT (panne_recherche_window_admin, combobox_admin, "combobox_admin");

  return panne_recherche_window_admin;
}

GtkWidget*
create_window1_admin (void)
{
  GtkWidget *window1_admin;
  GtkWidget *fixed10;
  GtkWidget *treeview1_admin;

  window1_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1_admin), _("les pannes"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window1_admin), fixed10);

  treeview1_admin = gtk_tree_view_new ();
  gtk_widget_show (treeview1_admin);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview1_admin, 24, 40);
  gtk_widget_set_size_request (treeview1_admin, 300, 200);

  g_signal_connect ((gpointer) treeview1_admin, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1_admin, window1_admin, "window1_admin");
  GLADE_HOOKUP_OBJECT (window1_admin, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window1_admin, treeview1_admin, "treeview1_admin");

  return window1_admin;
}

