/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "fonction.h"
int
main (int argc, char *argv[])
{
  GtkWidget *ajout_window_admin;
  GtkWidget *menu_window_admin;
  GtkWidget *affiche_window_admin;
  GtkWidget *traitment_window_admin;
  GtkWidget  *panne_window_admin;
  GtkWidget *treeviewpanneadmin;


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE ,PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 
  menu_window_admin = create_menu_window_admin ();
  gtk_widget_show (menu_window_admin);

  /*panne_window_admin = create_panne_window_admin ();
  gtk_widget_show (panne_window_admin);
  
  treeviewpanne=lookup_widget(panne_window_admin,"treeviewpanne");
  affichePANNE("debit.txt",treeviewpanne);*/

  gtk_main ();
  return 0;
}

